export const FETCH_REPOS_STARTED = 'FETCH_REPOS_STARTED';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const REPOS_FETCHED_STATUS = 'REPOS_FETCHED_STATUS';
export const UNMOUNT_REPOS = 'UNMOUNT_REPOS';

export const ENABLE_REPO_STARTED = 'ENABLE_REPO_STARTED';
export const ENABLE_REPO_SUCCESS = 'ENABLE_REPO_SUCCESS';
export const REPO_ENABLED_STATUS = 'REPO_ENABLED_STATUS';

export const FETCH_ACTIVE_REPOS_STARTED = 'FETCH_ACTIVE_REPOS_STARTED';
export const FETCH_ACTIVE_REPOS_SUCCESS = 'FETCH_ACTIVE_REPOS_SUCCESS';
export const ACTIVE_REPOS_FETCHED_STATUS = 'ACTIVE_REPOS_FETCHED_STATUS';
export const UNMOUNT_ACTIVE_REPOS = 'UNMOUNT_ACTIVE_REPOS';

export const FETCH_TESTS_STARTED = 'FETCH_TESTS_STARTED';
export const FETCH_TESTS_SUCCESS = 'FETCH_TESTS_SUCCESS';
export const TESTS_FETCHED_STATUS = 'TESTS_FETCHED_STATUS';
export const UNMOUNT_TESTS = 'UNMOUNT_TESTS';

export const FETCH_TEST_DETAILS_STARTED = 'FETCH_TEST_DETAILS_STARTED';
export const FETCH_TEST_DETAILS_SUCCESS = 'FETCH_TEST_DETAILS_SUCCESS';
export const TEST_DETAILS_FETCHED_STATUS = 'TEST_DETAILS_FETCHED_STATUS';
export const UNMOUNT_TESTS_DETAILS = 'UNMOUNT_TESTS_DETAILS';
export const UNMOUNT_TEST_PREVIOUS = 'UNMOUNT_TEST_PREVIOUS';

export const FETCH_TEST_METRICS_STARTED = 'FETCH_TEST_METRICS_STARTED';
export const FETCH_TEST_METRICS_SUCCESS = 'FETCH_TEST_METRICS_SUCCESS';
export const TEST_METRICS_FETCHED_STATUS = 'TEST_METRICS_FETCHED_STATUS';

export const FETCH_TEST_PASS_FAIL_STARTED = 'FETCH_TEST_PASS_FAIL_STARTED';
export const FETCH_TEST_PASS_FAIL_SUCCESS = 'FETCH_TEST_PASS_FAIL_SUCCESS';
export const TEST_PASS_FAIL_FETCHED_STATUS = 'TEST_PASS_FAIL_FETCHED_STATUS';

export const FETCH_CURRENT_TEST_STARTED = 'FETCH_CURRENT_TEST_STARTED';
export const FETCH_CURRENT_TEST_SUCCESS = 'FETCH_CURRENT_TEST_SUCCESS';
export const CURRENT_TEST_FETCHED_STATUS = 'CURRENT_TEST_FETCHED_STATUS';

export const FETCH_TESTS_SUITES_STARTED = 'FETCH_TESTS_SUITES_STARTED';
export const FETCH_TESTS_SUITES_SUCCESS = 'FETCH_TESTS_SUITES_SUCCESS';
export const TESTS_SUITES_FETCHED_STATUS = 'TESTS_SUITES_FETCHED_STATUS';
export const UNMOUNT_TESTS_SUITES = 'UNMOUNT_TESTS_SUITES';

export const FETCH_SUITE_DETAILS_STARTED = 'FETCH_SUITE_DETAILS_STARTED';
export const FETCH_SUITE_DETAILS_SUCCESS = 'FETCH_SUITE_DETAILS_SUCCESS';
export const SUITE_DETAILS_FETCHED_STATUS = 'SUITE_DETAILS_FETCHED_STATUS';
export const UNMOUNT_TEST_SUITE_DETAILS = 'UNMOUNT_TEST_SUITE_DETAILS';
export const UNMOUNT_TEST_SUITE_PREVIOUS = 'UNMOUNT_TEST_SUITE_PREVIOUS';

export const FETCH_CURRENT_TEST_SUITE_STARTED = 'FETCH_CURRENT_TEST_SUITE_STARTED';
export const FETCH_CURRENT_TEST_SUITE_SUCCESS = 'FETCH_CURRENT_TEST_SUITE_SUCCESS';
export const CURRENT_TEST_SUITE_FETCHED_STATUS = 'CURRENT_TEST_SUITE_FETCHED_STATUS';

export const FETCH_CURRENT_BUILD_STARTED = 'FETCH_CURRENT_BUILD_STARTED';
export const FETCH_CURRENT_BUILD_SUCCESS = 'FETCH_CURRENT_BUILD_SUCCESS';
export const CURRENT_BUILD_FETCHED_STATUS = 'CURRENT_BUILD_FETCHED_STATUS';

export const FETCH_BUILD_COMMIT_STARTED = 'FETCH_BUILD_COMMIT_STARTED';
export const FETCH_BUILD_COMMIT_SUCCESS = 'FETCH_BUILD_COMMIT_SUCCESS';
export const BUILD_COMMIT_FETCHED_STATUS = 'BUILD_COMMIT_FETCHED_STATUS';

export const FETCH_BUILD_COMMIT_TESTS_STARTED = 'FETCH_BUILD_COMMIT_TESTS_STARTED';
export const FETCH_BUILD_COMMIT_TESTS_SUCCESS = 'FETCH_BUILD_COMMIT_TESTS_SUCCESS';
export const BUILD_COMMIT_TESTS_FETCHED_STATUS = 'BUILD_COMMIT_TESTS_FETCHED_STATUS';
export const RESET_BUILD_COMMIT_TESTS = 'RESET_BUILD_COMMIT_TESTS';

export const FETCH_TIME_SAVED_STARTED = 'FETCH_TIME_SAVED_STARTED';
export const FETCH_TIME_SAVED_SUCCESS = 'FETCH_TIME_SAVED_SUCCESS';
export const TIME_SAVED_FETCHED_STATUS = 'TIME_SAVED_FETCHED_STATUS';

export const FETCH_CURRENT_COMMIT_STARTED = 'FETCH_CURRENT_COMMIT_STARTED';
export const FETCH_CURRENT_COMMIT_SUCCESS = 'FETCH_CURRENT_COMMIT_SUCCESS';
export const CURRENT_COMMIT_FETCHED_STATUS = 'CURRENT_COMMIT_FETCHED_STATUS';

export const COMMIT_TRIGGER_REBUILD_STATUS = 'COMMIT_TRIGGER_REBUILD_STATUS';
export const COMMIT_TRIGGER_REBUILD_STARTED = 'COMMIT_TRIGGER_REBUILD_STARTED';
export const COMMIT_TRIGGER_REBUILD_SUCCESS = 'COMMIT_TRIGGER_REBUILD_SUCCESS';

export const PERSIST_CURRENT_ORG = 'PERSIST_CURRENT_ORG';
export const PERSIST_ORGS = 'PERSIST_ORGS';
export const PERSIST_USER_INFO = 'PERSIST_USER_INFO';

export const FETCH_SUITE_METRICS_STARTED = 'FETCH_SUITE_METRICS_STARTED';
export const FETCH_SUITE_METRICS_SUCCESS = 'FETCH_SUITE_METRICS_SUCCESS';
export const SUITE_METRICS_FETCHED_STATUS = 'SUITE_METRICS_FETCHED_STATUS';

export const FETCH_SUITE_PASS_FAIL_STARTED = 'FETCH_SUITE_PASS_FAIL_STARTED';
export const FETCH_SUITE_PASS_FAIL_SUCCESS = 'FETCH_SUITE_PASS_FAIL_SUCCESS';
export const SUITE_PASS_FAIL_FETCHED_STATUS = 'SUITE_PASS_FAIL_FETCHED_STATUS';

export const FETCH_BUILDS_STARTED = 'FETCH_BUILDS_STARTED';
export const FETCH_BUILDS_SUCCESS = 'FETCH_BUILDS_SUCCESS';
export const BUILDS_FETCHED_STATUS = 'BUILDS_FETCHED_STATUS';

export const FETCH_BUILD_DETAILS_STARTED = 'FETCH_BUILD_DETAILS_STARTED';
export const FETCH_BUILD_DETAILS_SUCCESS = 'FETCH_BUILD_DETAILS_SUCCESS';
export const BUILD_DETAILS_FETCHED_STATUS = 'BUILD_DETAILS_FETCHED_STATUS';
export const FETCH_FLAKY_BUILD_DETAILS_STARTED = 'FETCH_FLAKY_BUILD_DETAILS_STARTED';
export const FETCH_FLAKY_BUILD_DETAILS_SUCCESS = 'FETCH_FLAKY_BUILD_DETAILS_SUCCESS';
export const FLAKY_BUILD_DETAILS_FETCHED_STATUS = 'FLAKY_BUILD_DETAILS_FETCHED_STATUS';
export const UNMOUNT_BUILDS = 'UNMOUNT_BUILDS';

export const FETCH_BUILD_METRICS_STARTED = 'FETCH_BUILD_METRICS_STARTED';
export const FETCH_BUILD_METRICS_SUCCESS = 'FETCH_BUILD_METRICS_SUCCESS';
export const BUILD_METRICS_FETCHED_STATUS = 'BUILD_METRICS_FETCHED_STATUS';
export const UNMOUNT_BUILD_TESTS = 'UNMOUNT_BUILD_TESTS';
export const UNMOUNT_METRICS_FETCHED = 'UNMOUNT_METRICS_FETCHED';
export const UNMOUNT_FLAKY_BUILD_DETAILS = 'UNMOUNT_FLAKY_BUILD_DETAILS';

export const COMMITS_FETCHED_STATUS = 'COMMITS_FETCHED_STATUS';
export const FETCH_BUILD_LOGS_BLOB_URL_STARTED = 'FETCH_BUILD_LOGS_BLOB_URL_STARTED';
export const FETCH_BUILD_LOGS_BLOB_URL_SUCCESS = 'FETCH_BUILD_LOGS_BLOB_URL_SUCCESS';
export const FETCH_BUILD_TASKS_STARTED = 'FETCH_BUILD_TASKS_STARTED';
export const FETCH_BUILD_TASKS_SUCCESS = 'FETCH_BUILD_TASKS_SUCCESS';
export const FETCH_COMMITS_STARTED = 'FETCH_COMMITS_STARTED';
export const FETCH_COMMITS_SUCCESS = 'FETCH_COMMITS_SUCCESS';
export const UNMOUNT_BUILD_LOGS = 'UNMOUNT_BUILD_LOGS';
export const UNMOUNT_COMMITS = 'UNMOUNT_COMMITS';

export const FETCH_COMMIT_BUILDS_STARTED = 'FETCH_COMMIT_BUILDS_STARTED';
export const FETCH_COMMIT_BUILDS_SUCCESS = 'FETCH_COMMIT_BUILDS_SUCCESS';
export const COMMIT_BUILDS_FETCHED_STATUS = 'COMMIT_BUILDS_FETCHED_STATUS';

export const FETCH_IMPACTED_TESTS_STARTED = 'FETCH_IMPACTED_TESTS_STARTED';
export const FETCH_IMPACTED_TESTS_SUCCESS = 'FETCH_IMPACTED_TESTS_SUCCESS';
export const IMPACTED_TESTS_FETCHED_STATUS = 'IMPACTED_TESTS_FETCHED_STATUS';
export const UNMOUNT_IMPACTED_TESTS = 'UNMOUNT_IMPACTED_TESTS';

export const FETCH_UNIMPACTED_TESTS_STARTED = 'FETCH_UNIMPACTED_TESTS_STARTED';
export const FETCH_UNIMPACTED_TESTS_SUCCESS = 'FETCH_UNIMPACTED_TESTS_SUCCESS';
export const UNIMPACTED_TESTS_FETCHED_STATUS = 'UNIMPACTED_TESTS_FETCHED_STATUS';

export const FETCH_CONTRIBUTORS_STARTED = 'FETCH_CONTRIBUTORS_STARTED';
export const FETCH_CONTRIBUTORS_SUCCESS = 'FETCH_CONTRIBUTORS_SUCCESS';
export const CONTRIBUTORS_FETCHED_STATUS = 'CONTRIBUTORS_FETCHED_STATUS';
export const UNMOUNT_CONTRIBUTORS = 'UNMOUNT_CONTRIBUTORS';

export const FETCH_ORGS_STARTED = 'FETCH_ORGS_STARTED';
export const FETCH_ORGS_SUCCESS = 'FETCH_ORGS_SUCCESS';
export const ORGS_FETCHED_STATUS = 'ORGS_FETCHED_STATUS';

export const FETCH_INSIGHTS_STARTED = 'FETCH_INSIGHTS_STARTED';
export const FETCH_INSIGHTS_SUCCESS = 'FETCH_INSIGHTS_SUCCESS';
export const INSIGHTS_FETCHED_STATUS = 'INSIGHTS_FETCHED_STATUS';
export const UNMOUNT_INSIGHTS = 'UNMOUNT_INSIGHTS';

export const TRENDS_FETCH_BUILDS_BY_DATE_STARTED = 'TRENDS_FETCH_BUILDS_BY_DATE_STARTED';
export const TRENDS_FETCH_BUILDS_BY_DATE_SUCCESS = 'TRENDS_FETCH_BUILDS_BY_DATE_SUCCESS';
export const TRENDS_FETCH_TESTS_BY_COMMIT_STARTED = 'TRENDS_FETCH_TESTS_BY_COMMIT_STARTED';
export const TRENDS_FETCH_TESTS_BY_COMMIT_SUCCESS = 'TRENDS_FETCH_TESTS_BY_COMMIT_SUCCESS';
export const TRENDS_FETCH_CUMULATIVE_TESTS_BY_DATE_STARTED =
  'TRENDS_FETCH_CUMULATIVE_TESTS_BY_DATE_STARTED';
export const TRENDS_FETCH_CUMULATIVE_TESTS_BY_DATE_SUCCESS =
  'TRENDS_FETCH_CUMULATIVE_TESTS_BY_DATE_SUCCESS';
export const TRENDS_FETCH_ANALYTICS_TABLE_DATA_BY_TYPE_STARTED =
  'TRENDS_FETCH_ANALYTICS_TABLE_DATA_BY_TYPE_STARTED';
export const TRENDS_FETCH_ANALYTICS_TABLE_DATA_BY_TYPE_SUCCESS =
  'TRENDS_FETCH_ANALYTICS_TABLE_DATA_BY_TYPE_SUCCESS';
export const TRENDS_UNMOUNT = 'TRENDS_UNMOUNT';

export const INSIGHTS_FLAKY_TESTS_FETCH_GRAPH_DATA_STARTED =
  'INSIGHTS_FLAKY_TESTS_FETCH_GRAPH_DATA_STARTED';
export const INSIGHTS_FLAKY_TESTS_FETCH_GRAPH_DATA_SUCCESS =
  'INSIGHTS_FLAKY_TESTS_FETCH_GRAPH_DATA_SUCCESS';
export const INSIGHTS_FLAKY_TESTS_FETCH_LIST_DATA_STARTED =
  'INSIGHTS_FLAKY_TESTS_FETCH_LIST_DATA_STARTED';
export const INSIGHTS_FLAKY_TESTS_FETCH_LIST_DATA_SUCCESS =
  'INSIGHTS_FLAKY_TESTS_FETCH_LIST_DATA_SUCCESS';
export const INSIGHTS_FLAKY_TESTS_UNMOUNT = 'INSIGHTS_FLAKY_TESTS_UNMOUNT';

export const IMPORT_CUSTOM_REPO_STARTED = 'IMPORT_CUSTOM_REPO_STARTED';
export const IMPORT_CUSTOM_REPO_SUCCESS = 'IMPORT_CUSTOM_REPO_SUCCESS';
export const IMPORT_CUSTOM_REPO_STATUS = 'IMPORT_CUSTOM_REPO_STATUS';

export const COMMIT_COVERAGE_STARTED = 'COMMIT_COVERAGE_STARTED';
export const COMMIT_COVERAGE_SUCCESS = 'COMMIT_COVERAGE_SUCCESS';
export const COMMIT_COVERAGE_FETCHED_STATUS = 'COMMIT_COVERAGE_FETCHED_STATUS';

export const SETTINGS_FETCH_ORG_CREDITS_STARTED = 'SETTINGS_FETCH_ORG_CREDITS_STARTED';
export const SETTINGS_FETCH_ORG_CREDITS_SUCCESS = 'SETTINGS_FETCH_ORG_CREDITS_SUCCESS';
export const SETTINGS_FETCH_USER_USAGE_STARTED = 'SETTINGS_FETCH_USER_USAGE_STARTED';
export const SETTINGS_FETCH_USER_USAGE_SUCCESS = 'SETTINGS_FETCH_USER_USAGE_SUCCESS';
export const SETTINGS_FETCH_SYNAPSE_COUNT_STARTED = 'SETTINGS_FETCH_SYNAPSE_COUNT_STARTED';
export const SETTINGS_FETCH_SYNAPSE_COUNT_SUCCESS = 'SETTINGS_FETCH_SYNAPSE_COUNT_SUCCESS';
export const SETTINGS_SET_USER_ACTIVE_STARTED = 'SETTINGS_SET_USER_ACTIVE_STARTED';
export const SETTINGS_SET_USER_ACTIVE_SUCCESS = 'SETTINGS_SET_USER_ACTIVE_SUCCESS';
export const SETTINGS_UNMOUNT = 'SETTINGS_UNMOUNT';

export const SETTINGS_VALIDATE_YAML_CONFIG_STARTED = 'SETTINGS_VALIDATE_YAML_CONFIG_STARTED';
export const SETTINGS_VALIDATE_YAML_CONFIG_SUCCESS = 'SETTINGS_VALIDATE_YAML_CONFIG_SUCCESS';

export const REPO_SETTINGS_ADD_POSTMERGE_CONFIG_STARTED =
  'REPO_SETTINGS_ADD_POSTMERGE_CONFIG_STARTED';
export const REPO_SETTINGS_ADD_POSTMERGE_CONFIG_SUCCESS =
  'REPO_SETTINGS_ADD_POSTMERGE_CONFIG_SUCCESS';
export const REPO_SETTINGS_FETCH_BRANCHES_LIST_STARTED =
  'REPO_SETTINGS_FETCH_BRANCHES_LIST_STARTED';
export const REPO_SETTINGS_FETCH_BRANCHES_LIST_SUCCESS =
  'REPO_SETTINGS_FETCH_BRANCHES_LIST_SUCCESS';
export const REPO_SETTINGS_FETCH_BRANCHES_PREONBOARDING_LIST_STARTED =
  'REPO_SETTINGS_FETCH_BRANCHES_PREONBOARDING_LIST_STARTED';
export const REPO_SETTINGS_FETCH_BRANCHES_PREONBOARDING_LIST_SUCCESS =
  'REPO_SETTINGS_FETCH_BRANCHES_PREONBOARDING_LIST_SUCCESS';
export const REPO_SETTINGS_FETCH_POSTMERGE_CONFIG_LIST_STARTED =
  'REPO_SETTINGS_FETCH_POSTMERGE_CONFIG_LIST_STARTED';
export const REPO_SETTINGS_FETCH_POSTMERGE_CONFIG_LIST_SUCCESS =
  'REPO_SETTINGS_FETCH_POSTMERGE_CONFIG_LIST_SUCCESS';
export const REPO_SETTINGS_UNMOUNT = 'REPO_SETTINGS_UNMOUNT';
export const REPO_SETTINGS_UPDATE_POSTMERGE_CONFIG_STARTED =
  'REPO_SETTINGS_UPDATE_POSTMERGE_CONFIG_STARTED';
export const REPO_SETTINGS_UPDATE_POSTMERGE_CONFIG_SUCCESS =
  'REPO_SETTINGS_UPDATE_POSTMERGE_CONFIG_SUCCESS';

export const REPO_SETTINGS_DELINK_REPO_STARTED = 'REPO_SETTINGS_DELINK_REPO_STARTED';
export const REPO_SETTINGS_DELINK_REPO_SUCCESS = 'REPO_SETTINGS_DELINK_REPO_SUCCESS';

/** FTM Configuration Actions */
export const REPO_SETTINGS_ADD_FTM_CONFIG_STARTED = 'REPO_SETTINGS_ADD_FTM_CONFIG_STARTED';
export const REPO_SETTINGS_ADD_FTM_CONFIG_SUCCESS = 'REPO_SETTINGS_ADD_FTM_CONFIG_SUCCESS';
export const REPO_SETTINGS_FETCH_FTM_CONFIG_LIST_STARTED =
  'REPO_SETTINGS_FETCH_FTM_CONFIG_LIST_STARTED';
export const REPO_SETTINGS_FETCH_FTM_CONFIG_LIST_SUCCESS =
  'REPO_SETTINGS_FETCH_FTM_CONFIG_LIST_SUCCESS';
export const REPO_SETTINGS_UPDATE_FTM_CONFIG_STARTED = 'REPO_SETTINGS_UPDATE_FTM_CONFIG_STARTED';
export const REPO_SETTINGS_UPDATE_FTM_CONFIG_SUCCESS = 'REPO_SETTINGS_UPDATE_FTM_CONFIG_SUCCESS';
